[build]
  command = "npm ci --no-audit --no-fund || npm install --ci --no-audit --no-fund; npm run whereami; npm run prebuild; npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
