[build]
  command = "npm ci --no-audit --no-fund || npm install --no-audit --no-fund; npm run whereami; npm run prebuild; npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
