[build]
  command = "npm ci --include=dev --no-audit --no-fund || npm install --include=dev --no-audit --no-fund && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.7.0"
